#!/bin/sh
# Generates env-config.js for a bare nginx (non-Docker) deployment.
#
# Usage:
#   1. Copy dist/ to your nginx webroot (e.g. /usr/share/nginx/html).
#   2. Set the required environment variables (or source a .env file):
#        export NEXTCLOUD_WEBDAV_SERVER=https://cloud.example.com
#        export CNC_APP_USER=cnc_user
#        export CNC_APP_PASSWORD=cnc_password
#      Or source from a file:
#        set -a && . /path/to/.env && set +a
#   3. Run this script, pointing WEBROOT at your nginx html directory:
#        WEBROOT=/usr/share/nginx/html ./scripts/gen-env-config.sh
#
# The script writes env-config.js to $WEBROOT (defaults to ./dist).

WEBROOT="${WEBROOT:-./dist}"

# Escape a value for safe embedding inside a JS double-quoted string.
js_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

NEXTCLOUD_WEBDAV_SERVER_ESC=$(js_escape "${NEXTCLOUD_WEBDAV_SERVER:-}")
CNC_APP_USER_ESC=$(js_escape "${CNC_APP_USER:-}")
CNC_APP_PASSWORD_ESC=$(js_escape "${CNC_APP_PASSWORD:-}")

cat > "${WEBROOT}/env-config.js" << EOF
// Generated by scripts/gen-env-config.sh — do not edit manually.
window._env = {
  NEXTCLOUD_WEBDAV_SERVER: "${NEXTCLOUD_WEBDAV_SERVER_ESC}",
  CNC_APP_USER: "${CNC_APP_USER_ESC}",
  CNC_APP_PASSWORD: "${CNC_APP_PASSWORD_ESC}"
};
EOF

echo "env-config.js written to ${WEBROOT}/env-config.js"
